application: townfloor
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /scripts
  static_dir: scripts

- url: /styles
  static_dir: styles

- url: /views
  static_dir: views

- url: /fonts
  static_dir: fonts

- url: /lib
  static_dir: lib

- url: .*
  static_files: index.html
  upload: index.html

libraries:
- name: webapp2
  version: "2.5.2"
